server:
  port: 8888

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/vamsikrishna-ch07/config-repo
          clone-on-start: true
          default-label: main

